<a href="https://colab.research.google.com/github/Akshattt4096/Python---data-visualization-/blob/main/dsp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to Colab!

In [6]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("/insurance - insurance.csv")

In [4]:
df.shape

(1338, 7)

In [7]:
columns = list(df.columns)
print(columns)

['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'expenses']

In [8]:
df.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [9]:
df.describe()

               age          bmi     children      expenses
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.665471     1.094918  13270.422414
std      14.049960     6.098382     1.205493  12110.011240
min      18.000000    16.000000     0.000000   1121.870000
25%      27.000000    26.300000     0.000000   4740.287500
50%      39.000000    30.400000     1.000000   9382.030000
75%      51.000000    34.700000     2.000000  16639.915000
max      64.000000    53.100000     5.000000  63770.430000

In [10]:
print(df.isnull().sum())
print("Missing distribution values: ")
print(df.isnull().mean())

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64
Missing distribution values:
age         0.0
sex         0.0
bmi         0.0
children    0.0
smoker      0.0
region      0.0
expenses    0.0
dtype: float64

In [12]:
print("Column datatypes")
print(df.dtypes)

Column datatypes
age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
expenses    float64
dtype: object

In [16]:
print(df.duplicated().any())
print(df.duplicated())
print(df.shape)

True
0       False
1       False
2       False
3       False
4       False
        ...
1333    False
1334    False
1335    False
1336    False
1337    False
Length: 1338, dtype: bool
(1338, 7)

In [18]:
df["sex"].replace({"male":"1", "female":"0"}, inplace=True)
print(df.head)
print(df.shape)

<bound method NDFrame.head of       age sex   bmi  children smoker     region  expenses
0      19   0  27.9         0    yes  southwest  16884.92
1      18   1  33.8         1     no  southeast   1725.55
2      28   1  33.0         3     no  southeast   4449.46
3      33   1  22.7         0     no  northwest  21984.47
4      32   1  28.9         0     no  northwest   3866.86
...   ...  ..   ...       ...    ...        ...       ...
1333   50   1  31.0         3     no  northwest  10600.55
1334   18   0  31.9         0     no  northeast   2205.98
1335   18   0  36.9         0     no  southeast   1629.83
1336   21   0  25.8         0     no  southwest   2007.95
1337   61   0  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]>
(1338, 7)

In [20]:
arr= np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]

In [22]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

2
(2, 3)
6
int64

In [24]:
np.zeros((2,3))
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [8]:
arr =np.array([10,20,30,40,50])
print(arr[2])
print(arr+5)

30
[15 25 35 45 55]

In [29]:
print(arr[1:4])

[20 30 40]

In [30]:
a= np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]

In [9]:
print(np.sqrt(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
150
30.0
50